// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB4P0ZEm33NQc_mUV_vLsePSizTOKSWVg',
    appId: '1:1085183132592:web:ad0f2217a80c5acc150c75',
    messagingSenderId: '1085183132592',
    projectId: 'flowerappedit',
    authDomain: 'flowerappedit.firebaseapp.com',
    storageBucket: 'flowerappedit.appspot.com',
    measurementId: 'G-XLLLMT0S13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK7BEbuClpyIkGHgtX64XlzOqgNOOSUZk',
    appId: '1:1085183132592:android:3fb46de16c60c173150c75',
    messagingSenderId: '1085183132592',
    projectId: 'flowerappedit',
    storageBucket: 'flowerappedit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd6_1y-H8CcGyckZUVHG6KW0VmtzqlHCE',
    appId: '1:1085183132592:ios:3897f00560f2cb52150c75',
    messagingSenderId: '1085183132592',
    projectId: 'flowerappedit',
    storageBucket: 'flowerappedit.appspot.com',
    iosClientId: '1085183132592-74d4hdjdmiaffk0qdjidugjkq54bhrft.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd6_1y-H8CcGyckZUVHG6KW0VmtzqlHCE',
    appId: '1:1085183132592:ios:3897f00560f2cb52150c75',
    messagingSenderId: '1085183132592',
    projectId: 'flowerappedit',
    storageBucket: 'flowerappedit.appspot.com',
    iosClientId: '1085183132592-74d4hdjdmiaffk0qdjidugjkq54bhrft.apps.googleusercontent.com',
    iosBundleId: 'com.example.testt',
  );
}
